stm32f4xx_hal.o : stm32f4xx_hal.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_cortex.o : stm32f4xx_hal_cortex.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_crc.o : stm32f4xx_hal_crc.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_dma.o : stm32f4xx_hal_dma.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_dma_ex.o : stm32f4xx_hal_dma_ex.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_exti.o : stm32f4xx_hal_exti.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_flash.o : stm32f4xx_hal_flash.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_flash_ex.o : stm32f4xx_hal_flash_ex.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_flash_ramfunc.o : stm32f4xx_hal_flash_ramfunc.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_gpio.o : stm32f4xx_hal_gpio.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_pwr.o : stm32f4xx_hal_pwr.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_pwr_ex.o : stm32f4xx_hal_pwr_ex.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_rcc.o : stm32f4xx_hal_rcc.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_rcc_ex.o : stm32f4xx_hal_rcc_ex.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_tim.o : stm32f4xx_hal_tim.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_tim_ex.o : stm32f4xx_hal_tim_ex.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_uart.o : stm32f4xx_hal_uart.c
	$(CC) $(CC_OPTS) -c $<