main.o : main.c 
	$(CC) $(CC_OPTS) -c $<
	
stm32f4xx_hal_msp.o : stm32f4xx_hal_msp.c
	$(CC) $(CC_OPTS) -c $<

stm32f4xx_it.o : stm32f4xx_it.c
	$(CC) $(CC_OPTS) -c $<

syscalls.o : syscalls.c
	$(CC) $(CC_OPTS) -c $<

system_stm32f4xx.o : system_stm32f4xx.c
	$(CC) $(CC_OPTS) -c $<
	
stm32f407vg_startup.o : stm32f407vg_startup.c
	$(CC) $(CC_OPTS) -c $<