parse_message.o : parse_message.c
	$(CC) $(CC_OPTS) -c $<
	
receive_message_from_host.o : receive_message_from_host.c
	$(CC) $(CC_OPTS) -c $<
	
send_message_to_host.o : send_message_to_host.c
	$(CC) $(CC_OPTS) -c $<